# Generated by Django 6.0.3 on 2026-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically set when the object is created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatically updated when the object is modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Sender's name", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Sender's email address",
                        max_length=254,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Message subject", max_length=200),
                ),
                ("message", models.TextField(help_text="Message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Message status",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Sender's IP address", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_con_status_59d242_idx",
                    )
                ],
            },
        ),
    ]
