# Generated by Django 5.1 on 2024-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures')),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
