# Generated by Django 5.2.6 on 2025-11-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_newsposts_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='home_slider_pictures')),
            ],
        ),
    ]
