# Generated by Django 6.0.3 on 2026-03-28 13:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("destination", "0003_homeslider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destination",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
            },
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Home Slider",
                "verbose_name_plural": "Home Sliders",
            },
        ),
        migrations.AlterModelOptions(
            name="newsposts",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "News Post",
                "verbose_name_plural": "News Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AddField(
            model_name="destination",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Automatically set when the object is created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically updated when the object is modified",
            ),
        ),
        migrations.AddField(
            model_name="homeslider",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Automatically set when the object is created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeslider",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically updated when the object is modified",
            ),
        ),
        migrations.AddField(
            model_name="newsposts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Automatically set when the object is created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsposts",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically updated when the object is modified",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Automatically set when the object is created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimonial",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Automatically updated when the object is modified",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=models.TextField(help_text="Detailed description of the destination"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                help_text="Destination image", upload_to="pictures"
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Destination name", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="offer",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this destination on special offer?",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="price",
            field=models.IntegerField(
                default=0,
                help_text="Price for visiting this destination",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="image",
            field=models.ImageField(
                help_text="Slider image", upload_to="home_slider_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="title",
            field=models.CharField(help_text="Slider image title", max_length=200),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="category",
            field=models.CharField(
                db_index=True, help_text="Article category", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="content",
            field=models.TextField(help_text="Article content"),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="date",
            field=models.IntegerField(
                help_text="Day of the month (1-31)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="image",
            field=models.ImageField(
                help_text="Article cover image", upload_to="news_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="month",
            field=models.CharField(help_text="Month name", max_length=20),
        ),
        migrations.AlterField(
            model_name="newsposts",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Article title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author",
            field=models.CharField(
                db_index=True, help_text="Testimonial author's name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(help_text="Testimonial content"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="position",
            field=models.CharField(
                help_text="Author's position or title", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="destination",
            index=models.Index(
                fields=["offer", "-created_at"], name="destination_offer_bf1fd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destination",
            index=models.Index(fields=["price"], name="destination_price_23a227_idx"),
        ),
        migrations.AddIndex(
            model_name="newsposts",
            index=models.Index(
                fields=["category", "-created_at"],
                name="destination_categor_a9cd59_idx",
            ),
        ),
    ]
